- name: snbt tasks for test1
  hosts: localhost
  connection: local
  tasks:
    - name: Compile produce  using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za/za-service/service-produce 
        mvn clean package -DskipTests
      register: maven_output
      tags:
      - produce

    - name: Compile frpza using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za 
        mvn clean package -DskipTests
      register: maven_output
      tags:
      - za

    - name: Compile produce-server  using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za/za-service/service-produce/service-produce-server
        mvn clean package -DskipTests
      register: maven_output
      tags:
      - produce-server

    - name: Display Maven output
      debug:
        var: maven_output.stdout_lines
      tags:
      - produce
      - produce-server
      - za
    