- hosts: happygo
  remote_user: root
  become: yes
  tasks:
   - name: Create log file
     file:
        path: /tmp/api.log
        state: touch
        owner: root
        group: root
        mode: '0644'  
   - name: check server pid
     shell: ps -ef | grep 'buyer' | grep 'java' | grep -v grep | awk '{print $2}'
     ignore_errors: True
     register: checkBuyer_output
     tags:
     - checkBuyer

   - name: deploy all server
     shell: | 
      cd /home/source
      sh ./api.sh > /tmp/api.log
     register: script_api_output
     async: 600
     poll: 10      
     tags:
     - deployALL
     
   - name: deploy buyerapi server
     shell: | 
        cd /home/source 
        sh ./startAPISingle.sh buyer > /tmp/buyer.log       
     register: buyerapi_output
     async: 3600
     poll: 10
     tags:
     - deployBuyer
  
   - name: Display checkBuyer output
     debug:
        var: checkBuyer_output.stdout_lines
     tags:
     - checkBuyer

   - name: Fetch deployALL script API log
     fetch:
       src: /tmp/api.log
       dest: ./api.log
     when: script_api_output.changed
     tags:
      - deployALL
   - name: Fetch deployBuyer script API log
     fetch:
       src: /tmp/buyer.log
       dest: ./buyer.log
     when: buyerapi_output.changed
     tags:
      - deployBuyer

   - name: Check nohup.log file status
     stat:
        path: /home/source/api/nohup.out
     register: out_log_file
     async: 300
     poll: 10     
     tags:
     - nohup

   - name: Fetch new out log content
     fetch:
        src: /home/source/api/nohup.out
        dest: ./nohup.log
        flat: yes
     when: out_log_file.stat.exists and out_log_file.stat.size > 0 and out_log_file.stat.checksum != lookup('file', './nohup.log', checksum_algorithm='sha1')      
     tags:
       - nohup


   - name: sslBack existing ssl cert files for happygo-server
     shell: | 
       cd /etc/nginx
       sh ./sslback.sh
     register: remote_output
     tags: sslUpload

   - name: Pause before sslUpload
     pause:
        seconds: 3      # 延迟 5 秒
     tags: sslUpload

   - name: Upload certs file to remote server
     copy:
      src: /Users/huguiqi/Documents/私有文档/小程序开发/20240715_cert/
      dest: /etc/nginx/ssl/
      force: yes  # 强制覆盖
      owner: root
      group: root
      mode: '0644'
     ignore_errors: yes  # 忽略错误
     register: remote_output
     tags:
       - sslUpload

   - name: Pause before restart nginx
     pause:
        seconds: 2      # 延迟 2 秒
     tags: 
        - sslUpload

   - name: restart nginx for happygo-server
     shell: | 
       systemctl restart nginx
     register: remote_output
     tags: 
        - sslUpload
        - restartNginx


   - name: Display remoteStdout output
     debug:
      msg: "remoteStdout out: {{ remote_output }}"
     tags:
       - sslUpload
       - restartNginx
       - deployImFront
  
   - name: deploy im front
     shell: | 
        cd /home/source/happygo-front 
        git pull -f origin main
        cd im
        rm -rf ./dist
        yarn install
        yarn build
        systemctl restart nginx
     register: remote_output
     tags:
       - deployImFront

   - name: deploy manager front
     shell: | 
        cd /home/source/happygo-front 
        git pull -f origin main
        cd manager
        rm -rf ./dist
        yarn install
        yarn build
        systemctl restart nginx
     register: remote_output
     tags:
       - deployManagerFront
       

   - name: Debug inventory
     debug:
       msg: "debug inventory: {{ groups['happygo'] }}"